### ISSUE TITLE
什么时候文档能完整呢

### ISSUE THREAD

**Issue by jamninetyfive** [polyv/polyv-rn-vod-sdk-demo#1]
什么时候文档能完整呢

**Comment by lichangjielong** [comment]
您好，文档已经整理完毕。如果还有其他想了解的信息，请提出来，我们后续补充到文档中去。

**Comment by jamninetyfive** [comment]
重新看了下文档 貌似不是免费使用的对吗？
是只能播放你们提供的视频对么？

**Comment by xieyunjia** [comment]
是到，需要在保利威视频云平台 http://www.polyv.net/ 注册账号，并开通相关服务。

**Comment by jamninetyfive** [comment]
好的谢谢，这么好的SDK 还是希望能剥离一下 能直接播放网络视频 本地视频。～

**Comment by xieyunjia** [comment]
不客气
