### ISSUE TITLE
按照文档继承后模拟器运行报错

### ISSUE THREAD

**Issue by Hel5ing** [polyv/polyv-rn-vod-sdk-demo#21]
`Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.polyv.android:polyvPlayer:2.13.2.
     Required by:
         project :app > project :polyvsdk
      > Could not resolve net.polyv.android:polyvPlayer:2.13.2.
         > Could not get resource 'https://maven.google.com/net/polyv/android/polyvPlayer/2.13.2/polyvPlayer-2.13.2.pom'.
            > Could not GET 'https://maven.google.com/net/polyv/android/polyvPlayer/2.13.2/polyvPlayer-2.13.2.pom'.
               > Connect to maven.google.com:443 [maven.google.com/142.251.43.14] failed: Connection timed out: connect
   > Could not resolve net.polyv.android:polyvPlayerABI:1.9.7.
     Required by:
         project :app > project :polyvsdk
      > Could not resolve net.polyv.android:polyvPlayerABI:1.9.7.
         > Could not get resource 'https://maven.google.com/net/polyv/android/polyvPlayerABI/1.9.7/polyvPlayerABI-1.9.7.pom'.
            > Could not GET 'https://maven.google.com/net/polyv/android/polyvPlayerABI/1.9.7/polyvPlayerABI-1.9.7.pom'.
               > Connect to maven.google.com:443 [maven.google.com/142.251.43.14] failed: Connection timed out: connect
   > Could not resolve net.polyv.android:polyvDownload:2.13.0.
     Required by:
         project :app > project :polyvsdk
      > Could not resolve net.polyv.android:polyvDownload:2.13.0.
         > Could not get resource 'https://maven.google.com/net/polyv/android/polyvDownload/2.13.0/polyvDownload-2.13.0.pom'.
            > Could not GET 'https://maven.google.com/net/polyv/android/polyvDownload/2.13.0/polyvDownload-2.13.0.pom'.
               > Connect to maven.google.com:443 [maven.google.com/142.251.43.14] failed: Connection timed out: connect
   > Could not resolve net.polyv.android:polyvScreencast:0.2.1.
     Required by:
         project :app > project :polyvsdk
      > Could not resolve net.polyv.android:polyvScreencast:0.2.1.
         > Could not get resource 'https://maven.google.com/net/polyv/android/polyvScreencast/0.2.1/polyvScreencast-0.2.1.pom'.
            > Could not GET 'https://maven.google.com/net/polyv/android/polyvScreencast/0.2.1/polyvScreencast-0.2.1.pom'.
               > Connect to maven.google.com:443 [maven.google.com/142.251.43.14] failed: Connection timed out: connect
   > Could not resolve net.polyv.android:polyvUpload:2.3.1.
     Required by:
         project :app > project :polyvsdk
      > Could not resolve net.polyv.android:polyvUpload:2.3.1.
         > Could not get resource 'https://maven.google.com/net/polyv/android/polyvUpload/2.3.1/polyvUpload-2.3.1.pom'.
            > Could not GET 'https://maven.google.com/net/polyv/android/polyvUpload/2.3.1/polyvUpload-2.3.1.pom'.
               > Connect to maven.google.com:443 [maven.google.com/142.251.43.14] failed: Connection timed out: connect
   > Could not resolve net.polyv.android:polyvSub:2.13.0.
     Required by:
         project :app > project :polyvsdk
      > Could not resolve net.polyv.android:polyvSub:2.13.0.
         > Could not get resource 'https://maven.google.com/net/polyv/android/polyvSub/2.13.0/polyvSub-2.13.0.pom'.
            > Could not GET 'https://maven.google.com/net/polyv/android/polyvSub/2.13.0/polyvSub-2.13.0.pom'.
               > Connect to maven.google.com:443 [maven.google.com/142.251.43.14] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

**Comment by Hel5ing** [comment]
自己解决了，再android\build.gradle中allprojects中添加以下代码
`maven {
            credentials {
                username '609cc5623a10edbf36da9615'
                password 'EbkbzTNHRJ=P'
            }
            url 'https://packages.aliyun.com/maven/repository/2102846-release-8EVsoM/'
        }`

**Comment by Hel5ing** [comment]
自己解决了，在android\build.gradle中allprojects中添加以下代码

`maven {
            credentials {
                username '609cc5623a10edbf36da9615'
                password 'EbkbzTNHRJ=P'
            }
            url 'https://packages.aliyun.com/maven/repository/2102846-release-8EVsoM/'
        }`

**Comment by Imagine-Brian** [comment]
我按照你的设置怎么不行啊？
