### ISSUE TITLE
IOS接入文档有错误

### ISSUE THREAD

**Issue by MythosMa** [polyv/polyv-rn-vod-sdk-demo#3]
原步骤：
iOS端集成步骤
	1	拷贝相关的Native代码 拷贝 demo项目的 **ios/PolyvVodRnDemo**文件夹 到 自身项目的 ios 目录下；

应该为：
iOS端集成步骤
	1	拷贝相关的Native代码 拷贝 demo项目的 **ios/PolyvVodRnModule**文件夹 到 自身项目的 ios 目录下；

**Comment by lichangjielong** [comment]
已经修改错误，感谢您的提醒。
